import { EventEmitter, ɵisPromise as isPromise } from '@angular/core';
import { AbstractControl, AbstractControlOptions, AsyncValidator, AsyncValidatorFn, FormControl, ValidationErrors, Validator, ValidatorFn, Validators } from '@angular/forms';
import { from, isObservable, Observable, Subscription } from 'rxjs';

export enum ShFormControlMode {
  Browse,
  Edit
}

export class ShFormControl<T = any> extends FormControl<T> {

  public browseFormat: string;
  public editFormat: string;
  public mode = ShFormControlMode.Browse;
  public id: string;
  public resource: string;
  public get currentFormat() {
    return ShFormControlMode.Browse ? this.browseFormat : this.editFormat;
  }

  /**
   * Specifies whether the group instance can be destroyed.
   */
  public canDestroy: boolean = true;

  /**
   * Multicasting observable used for control focus.
   */
  public readonly focus$: Observable<void> = new EventEmitter<void>();

  /**
   * The function that is used to determine the validity of this control synchronously.
   */
  public get warning(): ValidatorFn | null {
    return this._composedWarningFn;
  }
  public set warning(warningFn: ValidatorFn | null) {
    this._rawWarnings = this._composedWarningFn = warningFn;
  }
  /**
   * The function that is used to determine the validity of this control asynchronously.
   */
  public get asyncWarning(): AsyncValidatorFn | null {
    return this._composedAsyncWarningFn;
  }
  public set asyncWarning(asyncWarningFn: AsyncValidatorFn | null) {
    this._rawAsyncWarnings = this._composedAsyncWarningFn = asyncWarningFn;
  }
  public hasWarning(...params: any[]) {
    return !!this.warnings;
  }
  /**
   * An object containing any errors generated by failing warning,
   * or null if there are no errors.
   */
  public readonly warnings: ValidationErrors | null;
  private _hasOwnPendingAsyncWarning: boolean;
  /**
   * Subscription of the asynchronous warning validation.
   *
   */
  protected asyncWarningSubscription: Subscription;
  /**
  * Contains the result of merging synchronous validators into a single validator function
  * (combined using `Validators.compose`).
  *
  * @internal
  */
  private _composedWarningFn: ValidatorFn | null;
  /**
   * Contains the result of merging asynchronous validators into a single validator function
   * (combined using `Validators.composeAsync`).
   *
   * @internal
   */
  private _composedAsyncWarningFn: AsyncValidatorFn | null;

  /**
   * Synchronous validators as they were provided:
   *  - in `AbstractControl` constructor
   *  - as an argument while calling `setValidators` function
   *  - while calling the setter on the `validator` field (e.g. `control.validator = validatorFn`)
   *
   * @internal
   */
  private _rawWarnings: ValidatorFn | ValidatorFn[] | null;

  /**
   * Asynchronous validators as they were provided:
   *  - in `AbstractControl` constructor
   *  - as an argument while calling `setAsyncValidators` function
   *  - while calling the setter on the `asyncValidator` field (e.g. `control.asyncValidator =
   * asyncValidatorFn`)
   *
   * @internal
   */
  private _rawAsyncWarnings: AsyncValidatorFn | AsyncValidatorFn[] | null;

  constructor(
    formState?: any,
    validatorOrOpts?: ValidatorFn | ValidatorFn[] | AbstractControlOptions | null,
    asyncValidator?: AsyncValidatorFn | AsyncValidatorFn[] | null,
    warnings?: ValidatorFn | ValidatorFn[] | null,
    asyncWarnings?: AsyncValidatorFn | AsyncValidatorFn[] | null) {
    super(formState, validatorOrOpts, asyncValidator);
    this._rawWarnings = warnings;
    this._rawAsyncWarnings = asyncWarnings;
    this._composedWarningFn = coerceToWarning(this._rawWarnings);
    this._composedAsyncWarningFn = coerceToAsyncWarning(this._rawAsyncWarnings);
  }

  /**
   * Emits focus event on the control.
   */
  public focusControl(): void {
    (this.focus$ as EventEmitter<void>).emit();
  }

  updateValueAndValidity(opts: { onlySelf?: boolean, emitEvent?: boolean } = {}): void {
    super.updateValueAndValidity(opts);

    if (this.enabled) {
      if (this.asyncWarningSubscription) {
        this.asyncWarningSubscription.unsubscribe();
        this._hasOwnPendingAsyncWarning = false;
      }
      (this as unknown as { warnings: ValidationErrors | null }).warnings = this._runWarning();

      this._runAsyncWarning(opts.emitEvent);
    }
  }

  public setWarnings(warnings: ValidationErrors | null, opts: { emitEvent?: boolean } = {}): void {
    (this as unknown as { warnings: ValidationErrors | null }).warnings = warnings;
    // this._updateControlsErrors(opts.emitEvent !== false);
  }

  private _runWarning(): ValidationErrors | null {
    return this.warning ? this.warning(this) : null;
  }

  private _runAsyncWarning(emitEvent?: boolean): void {
    if (this.asyncWarning) {
      this._hasOwnPendingAsyncWarning = true;
      const obs = toObservable(this.asyncWarning(this));
      this.asyncWarningSubscription = obs.subscribe((warnings: ValidationErrors | null) => {
        this._hasOwnPendingAsyncWarning = false;
        this.setWarnings(warnings, { emitEvent });
      });
    }
  }

}

/**
 * Creates validator function by combining provided validators.
 */
function coerceToWarning(warning: ValidatorFn | ValidatorFn[] | null): ValidatorFn | null {
  return Array.isArray(warning) ? composeWarnings(warning) : warning || null;
}

/**
 * Creates async validator function by combining provided async validators.
 */
function coerceToAsyncWarning(asyncWarning?: AsyncValidatorFn | AsyncValidatorFn[] |
  null): AsyncValidatorFn | null {
  return Array.isArray(asyncWarning) ? composeAsyncWarnings(asyncWarning) :
    asyncWarning || null;
}

function composeWarnings(warnings: Array<Validator | ValidatorFn>): ValidatorFn | null {
  return warnings != null ? Validators.compose(normalizeWarnings<ValidatorFn>(warnings)) :
    null;
}

function composeAsyncWarnings(warnings: Array<AsyncValidator | AsyncValidatorFn>):
  AsyncValidatorFn | null {
  return warnings != null ?
    Validators.composeAsync(normalizeWarnings<AsyncValidatorFn>(warnings)) :
    null;
}

function normalizeWarnings<V>(warnings: (V | any | Validator | AsyncValidator)[]): V[] {
  return warnings.map(validator => {
    return isWarningFn<V>(validator) ?
      validator :
      ((c: AbstractControl) => validator.validate(c)) as unknown as V;
  });
}

function isWarningFn<V>(warning: V | Validator | AsyncValidator): warning is V {
  return !(warning as Validator).validate;
}

function toObservable(r: any): Observable<any> {
  const obs = isPromise(r) ? from(r) : r;
  if (!(isObservable(obs))) {
    throw new Error(`Expected validator to return Promise or Observable.`);
  }
  return obs;
}
