parameters:
- name: workDir
  displayName: workDir
  type: string
  default: $(System.DefaultWorkingDirectory)

steps:
- task: PowerShell@2
  displayName: npm ci
  inputs:
    targetType: inline
    workingDirectory: ${{ parameters.workDir }}
    script: |
      npm i --legacy-peer-deps --force
